#!/bin/sh

envsubst '${PROXY_UPSTREAM_PROMETHEUS_HOST}${PROXY_UPSTREAM_PROMETHEUS_PORT}${PROXY_UPSTREAM_NODEEXPORTER_HOST}${PROXY_UPSTREAM_NODEEXPORTER_PORT}${PROXY_UPSTREAM_GRAFANA_HOST}${PROXY_UPSTREAM_GRAFANA_PORT}${PROXY_UPSTREAM_CADVISOR_HOST}${PROXY_UPSTREAM_CADVISOR_PORT}' < /etc/nginx/nginx.conf.tpl > /etc/nginx/nginx.conf
nginx -g "daemon off;"
