{
 "title": "a Nginx Connections Overview",
 "description": "Shows stats built from the Prometheus Nginx status page exporter rebuy-de/nginx-exporter or ndiazg/nginx-prometheus-exporter.",
 "tags": [
  "nginx",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(nginx_up, namespace)"
   },
   {
    "name": "app",
    "query": "label_values(nginx_up{namespace=~\"$namespace\"}, app)"
   },
   {
    "name": "instance",
    "query": "label_values(nginx_up{namespace=~\"$namespace\",  app=~\"$app\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{namespace=~\"$namespace\", app=~\"$app\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processed Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_processed_total{instance=~\"$instance\", app=~\"$app\", stage=\"handled\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "[{{app}}] {{stage}} (Handled connections)"
    },
    {
     "expr": "irate(nginx_connections_processed_total{instance=~\"$instance\", app=~\"$app\", stage=\"accepted\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "[{{app}}] {{stage}} (Accepted client connections.)"
    },
    {
     "expr": "irate(nginx_connections_processed_total{instance=~\"$instance\", app=~\"$app\", stage=\"any\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "[{{app}}] {{stage}} (Client requests)"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"kubernetes-pods\", app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_current{state=\"active\", app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "[{{app}}] {{state}} (Active client connections including Waiting connections)",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "nginx_connections_current{state=\"reading\", app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "[{{app}}] {{state}} (Connections where nginx is reading the request header)"
    },
    {
     "expr": "nginx_connections_current{state=\"writing\", app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "[{{app}}] {{state}} (Connections where nginx is writing the response back to the client)"
    },
    {
     "expr": "nginx_connections_current{state=\"waiting\", app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "[{{app}}] {{state}} (Idle client connections waiting for a request)"
    }
   ]
  }
 ]
}